In [1]:
import numpy as np

In [2]:
d_14 = np.array([1,2,3,4,5])
print(d_14)

[1 2 3 4 5]


In [3]:
i_14 = np.array([[6,7,8,9,10],[11,12,13,14,15]])
print(i_14)

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [4]:
t_14 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[4,3,5,7]],[[2,3,4,5],[6,7,8,9]]])
print(t_14)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 4  3  5  7]]

 [[ 2  3  4  5]
  [ 6  7  8  9]]]


In [20]:
d_14.ndim

2

In [21]:
i_14.ndim

2

In [22]:
t_14.ndim

3

In [23]:
d_14.shape

(3, 4)

In [24]:
i_14.shape

(2, 5)

In [25]:
t_14.shape

(3, 2, 4)

In [27]:
d_14 = np.array([[2,4,6,8],[10,12,14,16],[18,20,22,24]])
print(d_14)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [28]:
d_14[0,2]

6

In [29]:
d_14[2,:]

array([18, 20, 22, 24])

In [30]:
d_14[:,1]

array([ 4, 12, 20])

In [31]:
d_14[0,1:2]

array([4])

In [32]:
d_14[0,0:2:4]

array([2])

In [35]:
d_14[0,1] = 50
print(d_14)

[[ 2 50  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [45]:
np.ones((1,3))

array([[1., 1., 1.]])

In [37]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [40]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [43]:
np.random.rand(2,3)

array([[0.10080069, 0.95297048, 0.77453997],
       [0.03306475, 0.08551801, 0.04202517]])

In [46]:
np.random.randint(2,8,size=(1,4))

array([[5, 5, 7, 2]])

NameError: name 'np' is not defined